In [3]:
import plotly.graph_objects as go
import os
import math
import numpy as np


In [4]:
def read_file(src):
    ch1_file = open(os.path.join(src))

    ch1 = ch1_file.read()

    ch1_file.close()
    
    ch1_lines = ch1.strip().split('\n')

    parsed_data = {}

    for i in range(23):
        key,value = ch1_lines[i].strip().split(',')[:2]
        parsed_data[key] = value
    
    volt = []

    for i in ch1_lines[25:]:
        try:
            volt.append(float(i.strip().split(',')[0]))        
        except:
            print('bad parsing data'+i)
        
    parsed_data['volt'] = volt
    return (parsed_data)


# RLC resonance graph (ref Volt vs Frequency)

In [5]:
src_1 = './RLC_R_11.91'
src_2 = './RLC_R_993.9'
src_3 = './RLC_R_2200'

data_1 = []
for i in os.listdir(src_1):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_1,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_1,i,'2.CSV'))
    data_1.append(channels)
volt_amp_1 = []
for i in range(len(data_1)):
    ch1_div = float(data_1[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_1[i]['ch2']['Vertical Scale'])

    _in = max(data_1[i]['ch1']['volt'])*ch1_div/32
    _out= max(data_1[i]['ch2']['volt'])*ch2_div/32 
    volt_amp_1.append(_out/_in)

data_2 = []
for i in os.listdir(src_2):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_2,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_2,i,'2.CSV'))
    data_2.append(channels)
volt_amp_2 = []
for i in range(len(data_2)):
    ch1_div = float(data_2[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_2[i]['ch2']['Vertical Scale'])

    _in = max(data_2[i]['ch1']['volt'])*ch1_div/32
    _out= max(data_2[i]['ch2']['volt'])*ch2_div/32 
    volt_amp_2.append(_out/_in)

data_3 = []
for i in os.listdir(src_3):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_3,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_3,i,'2.CSV'))
    data_3.append(channels)
volt_amp_3 = []
for i in range(len(data_3)):
    ch1_div = float(data_3[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_3[i]['ch2']['Vertical Scale'])

    _in = max(data_3[i]['ch1']['volt'])*ch1_div/32
    _out= max(data_3[i]['ch2']['volt'])*ch2_div/32 
    volt_amp_3.append(_out/_in)

frequency_1 = [2000+i*200 for i in range(26)]
frequency_2 = [1000+i*200 for i in range(41)]
frequency_3 = [3000+i*2000 for i in range(33)]
trace_1 = go.Scattergl(
    x=frequency_1,
    y=volt_amp_1,
    mode='markers',
    name= 'R = 11.91 , Q = 254.43 ' ,
)
trace_2 = go.Scattergl(
    x=frequency_2,
    y=volt_amp_2,
    mode='markers',
    name= 'R = 993.9 , Q = 3.05 ' ,
)
trace_3 = go.Scattergl(
    x=frequency_3,
    y=volt_amp_3,
    mode='markers',
    name= 'R = 2200 , Q = 1.37 ' ,
)

fig = go.Figure()
fig.add_trace(trace_1)
fig.add_trace(trace_2)
fig.add_trace(trace_3)


Xaxis_title = "Frequency"
Yaxis_title = "Amp ( Vout / Vin )"
fig['layout'].update(xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        legend_title='sources',
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )

fig.write_html('RLC_resonance_refvolt.html', auto_open=True)


# RLC resonance graph (abs volt)

In [6]:
src_1 = './RLC_R_11.91'
src_2 = './RLC_R_993.9'
src_3 = './RLC_R_2200'

data_1 = []
for i in os.listdir(src_1):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_1,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_1,i,'2.CSV'))
    data_1.append(channels)
volt_amp_1 = []
for i in range(len(data_1)):
    ch1_div = float(data_1[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_1[i]['ch2']['Vertical Scale'])

    _out= max(data_1[i]['ch2']['volt'])*ch2_div/32 
    volt_amp_1.append(_out)

data_2 = []
for i in os.listdir(src_2):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_2,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_2,i,'2.CSV'))
    data_2.append(channels)
volt_amp_2 = []
for i in range(len(data_2)):
    ch1_div = float(data_2[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_2[i]['ch2']['Vertical Scale'])

    _out= max(data_2[i]['ch2']['volt'])*ch2_div/32 
    volt_amp_2.append(_out)

data_3 = []
for i in os.listdir(src_3):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_3,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_3,i,'2.CSV'))
    data_3.append(channels)
volt_amp_3 = []
for i in range(len(data_3)):
    ch1_div = float(data_3[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_3[i]['ch2']['Vertical Scale'])

    _out= max(data_3[i]['ch2']['volt'])*ch2_div/32 
    volt_amp_3.append(_out)

frequency_1 = [2000+i*200 for i in range(26)]
frequency_2 = [1000+i*200 for i in range(41)]
frequency_3 = [3000+i*2000 for i in range(33)]
trace_1 = go.Scattergl(
    x=frequency_1,
    y=volt_amp_1,
    mode='markers',
    name= 'R = 11.91 , Q = 254.43 ' ,
)
trace_2 = go.Scattergl(
    x=frequency_2,
    y=volt_amp_2,
    mode='markers',
    name= 'R = 993.9 , Q = 3.05 ' ,
)
trace_3 = go.Scattergl(
    x=frequency_3,
    y=volt_amp_3,
    mode='markers',
    name= 'R = 2200 , Q = 1.37 ' ,
)

fig = go.Figure()
fig.add_trace(trace_1)
fig.add_trace(trace_2)
fig.add_trace(trace_3)


Xaxis_title = "Frequency"
Yaxis_title = "Volt ( V_R )"
fig['layout'].update(xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        legend_title='sources',
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )

fig.write_html('RLC_resonance_absvolt.html', auto_open=True)


# RLC resonance graph (Current)

In [7]:
src_1 = './RLC_R_11.91'
src_2 = './RLC_R_993.9'
src_3 = './RLC_R_2200'

data_1 = []
for i in os.listdir(src_1):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_1,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_1,i,'2.CSV'))
    data_1.append(channels)
volt_amp_1 = []
for i in range(len(data_1)):
    ch1_div = float(data_1[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_1[i]['ch2']['Vertical Scale'])

    _out= max(data_1[i]['ch2']['volt'])*ch2_div/32 
    volt_amp_1.append(_out/11.91)

data_2 = []
for i in os.listdir(src_2):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_2,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_2,i,'2.CSV'))
    data_2.append(channels)
volt_amp_2 = []
for i in range(len(data_2)):
    ch1_div = float(data_2[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_2[i]['ch2']['Vertical Scale'])

    _out= max(data_2[i]['ch2']['volt'])*ch2_div/32 
    volt_amp_2.append(_out/993.9)

data_3 = []
for i in os.listdir(src_3):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_3,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_3,i,'2.CSV'))
    data_3.append(channels)
volt_amp_3 = []
for i in range(len(data_3)):
    ch1_div = float(data_3[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_3[i]['ch2']['Vertical Scale'])

    _out= max(data_3[i]['ch2']['volt'])*ch2_div/32 
    volt_amp_3.append(_out/2200)

frequency_1 = [2000+i*200 for i in range(26)]
frequency_2 = [1000+i*200 for i in range(41)]
frequency_3 = [3000+i*2000 for i in range(33)]
trace_1 = go.Scattergl(
    x=frequency_1,
    y=volt_amp_1,
    mode='markers',
    name= 'R = 11.91 , Q = 254.43 ' ,
)
trace_2 = go.Scattergl(
    x=frequency_2,
    y=volt_amp_2,
    mode='markers',
    name= 'R = 993.9 , Q = 3.05 ' ,
)
trace_3 = go.Scattergl(
    x=frequency_3,
    y=volt_amp_3,
    mode='markers',
    name= 'R = 2200 , Q = 1.37 ' ,
)

fig = go.Figure()
fig.add_trace(trace_1)
fig.add_trace(trace_2)
fig.add_trace(trace_3)


Xaxis_title = "Frequency"
Yaxis_title = "Current Amp (A)"
fig['layout'].update(xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        legend_title='sources',
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )

fig.write_html('RLC_resonance_current.html', auto_open=True)


# Curve fitting

In [8]:
import numpy as np
from scipy.optimize import curve_fit

# Load data 

src_1 = './RLC_R_11.91'
src_2 = './RLC_R_993.9'
src_3 = './RLC_R_2200'

data_1 = []
for i in os.listdir(src_1):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_1,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_1,i,'2.CSV'))
    data_1.append(channels)

volt_amp_1 = []
curr_amp_1 = []
for i in range(len(data_1)):
    ch1_div = float(data_1[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_1[i]['ch2']['Vertical Scale'])

    _in = max(data_1[i]['ch1']['volt'])*ch1_div/32
    _out= max(data_1[i]['ch2']['volt'])*ch2_div/32 
    curr_amp_1.append(_out/11.91)
    volt_amp_1.append(_in)

data_2 = []
for i in os.listdir(src_2):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_2,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_2,i,'2.CSV'))
    data_2.append(channels)

volt_amp_2 = []
curr_amp_2 = []
for i in range(len(data_2)):
    ch1_div = float(data_2[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_2[i]['ch2']['Vertical Scale'])

    _in = max(data_2[i]['ch1']['volt'])*ch1_div/32
    _out= max(data_2[i]['ch2']['volt'])*ch2_div/32 
    curr_amp_2.append(_out/993.9)
    volt_amp_2.append(_in)

data_3 = []
for i in os.listdir(src_3):
    channels = {'ch1':'','ch2':''}
    channels['ch1'] = read_file(os.path.join(src_3,i,'1.CSV'))
    channels['ch2'] = read_file(os.path.join(src_3,i,'2.CSV'))
    data_3.append(channels)

volt_amp_3 = []
curr_amp_3 = []
for i in range(len(data_3)):
    ch1_div = float(data_3[i]['ch1']['Vertical Scale'])
    ch2_div = float(data_3[i]['ch2']['Vertical Scale'])

    _in = max(data_3[i]['ch1']['volt'])*ch1_div/32
    _out= max(data_3[i]['ch2']['volt'])*ch2_div/32 
    curr_amp_3.append(_out/2200)
    volt_amp_3.append(_in)

frequency_1 = [2000+i*200 for i in range(26)]
frequency_2 = [1000+i*200 for i in range(41)]
frequency_3 = [3000+i*2000 for i in range(33)]

In [9]:
print(volt_amp_1)

[8.4375, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.125, 7.5, 8.125, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75]


In [10]:
curr_amp_1 = [curr_amp_1[i] for i in range(len(curr_amp_1)) if volt_amp_1[i] == 8.75]
frequency_1 = [frequency_1[i] for i in range(len(frequency_1)) if volt_amp_1[i] == 8.75]

In [11]:
print(volt_amp_2)

[8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.125, 8.125, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.125, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75]


In [12]:
curr_amp_2 = [curr_amp_2[i] for i in range(len(curr_amp_2)) if volt_amp_2[i] == 8.75]
frequency_2 = [frequency_2[i] for i in range(len(frequency_2)) if volt_amp_2[i] == 8.75]

In [13]:
print(volt_amp_3)

[8.75, 8.75, 8.75, 8.75, 9.0625, 9.0625, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75, 8.75]


In [14]:
curr_amp_3 = [curr_amp_3[i] for i in range(len(curr_amp_3)) if volt_amp_3[i] == 8.75]
frequency_3 = [frequency_3[i] for i in range(len(frequency_3)) if volt_amp_3[i] == 8.75]

### Curv fitting
`CAUTION : THIS SECTION IS NOT WORKING WELL`

In [15]:
def f(x,R,L,C):
    X_c = 1/(2*np.pi*x*C)
    X_l = 2*np.pi*x*L
    return 8.75/np.sqrt(R**2+(X_l**2-X_c**2)**2)

In [16]:
R = 11.91
L = 93.27*10**(-3)
C = 10.157*10**(-9)

popt_1, pcov_1 = curve_fit(f,frequency_1,curr_amp_1,bounds=([0.95*R,0.95*L,0.95*C], [1.05*R,1.05*L,1.05*C]))
print(popt_1)
print(pcov_1)

[1.1910e+01 9.3270e-02 1.0157e-08]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.23667978e-01 -5.68702144e-08]
 [ 0.00000000e+00 -5.68702144e-08  3.41963179e-14]]


In [17]:
R = 993.9
L = 93.27*10**(-3)
C = 10.157*10**(-9)

popt_2, pcov_2 = curve_fit(f,frequency_2,curr_amp_2,bounds=([0.95*R,0.95*L,0.95*C], [1.05*R,1.05*L,1.05*C]))
print(popt_2)
print(pcov_2)

[9.46076708e+02 9.07889510e-02 1.03007133e-08]
[[ 3.08895661e-24 -1.87695677e-14  7.92413791e-20]
 [-1.87695677e-14  1.14050379e-04 -4.81497999e-10]
 [ 7.92413791e-20 -4.81497999e-10  2.09039270e-15]]


In [18]:
R = 2200
L = 93.27*10**(-3)
C = 10.157*10**(-9)

popt_3, pcov_3 = curve_fit(f,frequency_1,curr_amp_1,bounds=([0.95*R,0.95*L,0.95*C], [1.05*R,1.05*L,1.05*C]))
print(popt_3)
print(pcov_3)

[2.20000000e+03 9.00266474e-02 9.64915263e-09]
[[ 9.94499978e-19  3.02263457e-11 -4.17720072e-16]
 [ 3.02263457e-11  9.18684762e-04 -1.26959795e-08]
 [-4.17720072e-16 -1.26959795e-08  1.75458191e-13]]


In [19]:
R = 11.91
L = 93.27*10**(-3)
C = 10.157*10**(-9)

trace_1 = go.Scattergl(
    x=frequency_1,
    y=curr_amp_1,
    mode='markers',
    name= f'Experiment : \n R = {R:.2e} , L = {L:.2e} , C = {C:.2e} ' ,
)
num = 10000
df = 5200/num
x = [2000+i*df for i in range(num)]
y = [f(i,R,L,C) for i in x]
trace_2 = go.Scattergl(
    x=x,
    y=y,
    mode='markers',
    marker=dict(size=1),
    name= f'Fitting Curve : \n R = {popt_1[0]:.2e} , L = {popt_1[1]:.2e} , C = {popt_1[2]:.2e} ' ,
)



fig = go.Figure()
fig.add_trace(trace_1)
fig.add_trace(trace_2)

Xaxis_title = "Frequency"
Yaxis_title = "Current Amp (A)"
fig['layout'].update(xaxis_title=Xaxis_title,
                        yaxis_title=Yaxis_title,
                        legend_title='sources',
                        font=dict(family='Microsoft JhengHei', size=18,), xaxis=dict(tickangle=0)
                        )

fig.write_html('Output.html', auto_open=True)
